### ISSUE TITLE
Where should I write the "python convert.py <original accounts file>" command?

### ISSUE THREAD

**Issue by markus200331** [Marc3842h/Titan#125]
Where should I write the "python convert.py <original accounts file>" command?
and is there a limit to how many accounts I can add?

**Comment by Marc3842h** [comment]
In order to do so you need to install Python and add it to PATH.
Then you can launch a terminal and run the command. 

If you require more direct support without the delay of having to use GitHub issues, there are many people on the Titan discord which are able to help you in case you require assistance with installing Python or converting your accounts file.
