### ISSUE TITLE
Is reportbot really working?

### ISSUE THREAD

**Issue by superhumanz** [Marc3842h/Titan#39]
Hey Marc3842h,

I have reportbot-ed 5 accounts (11 reports each) successfully with matchid , with no success none of them got banned.
Please advised.

 
                                                                                                                          Thank you,JerkReject

**Comment by thestranger00** [comment]
I'm pretty sure reportbot is working as Zoner still works but yeah i also reportbotted 2x (22 reports) 3 spinbotters and ragers but none got banned even after 48 hours :P

**Comment by BoberMod** [comment]
Yes, yesterday i banned 2 fagg0ts, but there is no 100% chance that it will be banned. To OW can get another game or rounds, when he didnt play.

**Comment by smurfPrime** [comment]
as long as 8 rounds going into overwatch, a guy raging a single game should get banned 100%!

if a guy playing some legit games and maybe gets some reports in it too... chance are good but not best for OW to detect him
(IF he got good kda in the legit games some of this games can go into OW too)


I had same problems a week ago but since 1 week its working good (I god lucky?)
I do allways check if the guy is continuing playing or not (if profile is public)
And if he gets ban I check some rep bot sides for the BANlist to be sure my bot (Titan) worked.

last 5 days 3BANs 90% did by Titan (maybe 1 was playing too many games and got player reports, but i dont think so because everyone of them stopped playing after they game against me)

**Comment by Marc3842h** [comment]
Right now it looks like for some people its a Hit&Miss. I'd advise to check if any bot accounts received a blue banner saying a reported player was banned. Keep in mind that Griefing bans don't show up on public Steam profiles (and yes, it may happen that _some_ people that are **obviously raging** only receive a Griefing conviction - It happened to myself). 

I myself had much more success with Match ID than without, but also not 100% Hit rate.

**IMPORTANT TO KNOW IS* that Titan still has 6h cooldown in its index calculator. This is incorrect and the cooldown is in fact 12h. I'lm change that in the next few commits.

**Comment by jtmkungfu** [comment]
i believe it is because like what marc said ive gone on at least one of the alts and someone i recently reported was banned off of it

**Comment by Marc3842h** [comment]
As this discussion is kind of dead, I'll close this. People are reporting that this report bot works and you'll need to investigate if it doesn't work for you.
